import Sidebar from "@/components/Sidebar/Sidebar";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from "@/components/Header/Header";
import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className} suppressHydrationWarning={true}>
        <Toaster position="top-center" toastOptions={{ duration: 5000 }} />
        <div className="grid grid-cols-1 md:grid-cols-[auto_minmax(900px,_1fr)] bg-[#F1F5F9]">
          <Sidebar />
          <div className="p-4">
            <Header />
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
